### ISSUE TITLE
Fails unless .xcworkspace file exists

### ISSUE THREAD

**Issue by jsierles** [bh5-js/rctapp#2]
Will this be able to work only with xcodeproj files? Most RN projects don't have workspace files unless they are using Cocoapods.

**Comment by euforic** [comment]
I though I was checking if it was there and defaulting to xcodeproj. I will take a look

**Comment by euforic** [comment]
Fixed in 0.2.2 https://github.com/bh5-js/rctapp/commit/53bb209a817469d1bae54066c0a0c3ea6bcc3625
